language:
  - cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y cmake libboost-all-dev
env:
  - BUILD_TYPE="Debug"
  - BUILD_TYPE="Release"
  - BUILD_TYPE="RelWithDebInfo"
  - BUILD_TYPE="MinSizeRel"
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DASIO_HTTP_BUILD_EXAMPLES=ON -DASIO_HTTP_BUILD_TESTS=ON ..
  - make
  - ctest -V
